import Head from "next/head"
import Image from "next/image"
import Hero from "@/components/hero"
import Navbar from "@/components/navbar"
import Footer from "@/components/footer"
import Products from "@/components/products"
import { PrismaClient } from "@prisma/client"

export async function getStaticProps() {
  const prisma = new PrismaClient()
  const products = await prisma.products.findMany()

  return {
    props: { products },
  }
}

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar /> */}
      <Hero />
      {products && <Products products={products} />}
      <Footer />
    </>
  )
}
