import Head from "next/head"
import Image from "next/image"
import Hero from "@/components/hero"
import Navbar from "@/components/navbar"
import Footer from "@/components/footer"
import SplitDetails from "@/components/split-details"
import Layout from "@/components/layouts/layout"

export default function Home() {
  return (
    <>
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar /> */}
      {/* <Hero /> */}
      {/* <div className="max-w-[1110px] mx-auto"> */}
      {/* <SplitDetails /> */}
      {/* </div> */}
      {/* <Footer /> */}
      <Layout>
      </Layout>
    </>
  )
}
